// <auto-generated />
using System;
using CapitalBreweryBikeClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapitalBreweryBikeClub.Migrations.RouteDatabase
{
    [DbContext(typeof(RouteDatabaseContext))]
    [Migration("20190914030318_Notes")]
    partial class Notes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapitalBreweryBikeClub.Model.MemberInformation", b =>
                {
                    b.Property<string>("Email");

                    b.HasKey("Email");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Email = "mike.swart@gmail.com"
                        });
                });

            modelBuilder.Entity("CapitalBreweryBikeClub.Model.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("CreatedByEmail");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CapitalBreweryBikeClub.Model.RouteData", b =>
                {
                    b.Property<string>("RideWithGpsId");

                    b.Property<bool>("Available");

                    b.Property<string>("Info");

                    b.Property<string>("Link");

                    b.Property<string>("Mileage");

                    b.Property<string>("Name");

                    b.HasKey("RideWithGpsId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("CapitalBreweryBikeClub.Model.Note", b =>
                {
                    b.HasOne("CapitalBreweryBikeClub.Model.MemberInformation", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
