// <auto-generated />
using CapitalBreweryBikeClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapitalBreweryBikeClub.Migrations.RouteDatabase
{
    [DbContext(typeof(RouteDatabaseContext))]
    partial class RouteDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapitalBreweryBikeClub.Model.RouteData", b =>
                {
                    b.Property<string>("RideWithGpsId");

                    b.Property<bool>("Available");

                    b.Property<string>("Info");

                    b.Property<string>("Link");

                    b.Property<string>("Mileage");

                    b.Property<string>("Name");

                    b.HasKey("RideWithGpsId");

                    b.ToTable("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
